marketplace/freelancers/urls.py
from django.urls import path
from .views import (
    views,
    job,
    user
)

app_name = 'freelancer'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('jobs/', job.JobListView.as_view(), name='joblist'),
    path('job/create/', job.JobCreateView.as_view(), name='jobcreate'),
    path('job/<slug:slug>/', job.JobDetailView.as_view(), name='jobdetail')
]


# users views
urlpatterns += [
    path('accounts/update/<slug:slug>/',
         user.UserUpdateView.as_view(), name='userupdate'),
    path('job/accept/<slug:code>/', job.JobAcceptedRedirectView.as_view(),
         name='acceptjob'),
    path('jobs/accepted/', job.AcceptedJobListView.as_view(),
         name='acceptedjoblist'),
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('freelancers.urls', namespace='freelance')),
    path('accounts/', include('registration.backends.default.urls')),
]

marketplace/freelancers/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from datetime import date


class Job(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    code = models.UUIDField(default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=80)
    description = models.TextField()
    budget = models.DecimalField(max_digits=8, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    expired = models.DateField()
    concluded = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Job"
        verbose_name_plural = "Jobs"
        ordering = ['created', '-concluded', 'expired']

    def __str__(self):
        return '{}'.format(self.title)

    @property
    def available(self):
        return not self.accept_set.filter(
            reject=False
        ) and self.expired > date.today()


class Accept(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reject = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Accept"
        verbose_name_plural = "Accepted"

    def __str__(self):
        pass

marketplace/freelancers/forms/job.py
from django import forms
from ..models import Job
from datetime import date


class JobForm(forms.ModelForm):

    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mt-4',
                'autocomplete': 'off',
                'required': 'required',
            })
    )
    budget = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'number',
                'autocomplete': 'off',
                'required': 'required',
                'min': 0.00,
                'step': 0.01
            })
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control md-textarea',
                'autocomplete': 'off',
                'required': 'required',
            })
    )
    expired = forms.DateField(
        initial=date.today,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'date',
                'autocomplete': 'off',
                'required': 'required',
            }),
        help_text='Expiration day'
    )

    class Meta:
        model = Job
        fields = (
            'title',
            'description',
            'budget',
            'expired'
        )

    def clean_expired(self):
        expired = self.cleaned_data.get('expired')
        print(expired)
        if expired < date.today():
            raise forms.ValidationError("The date cannot be in the past!")
        return expired

marketplace/freelancers/forms/user.py
from django import forms
from django.contrib.auth import get_user_model
UserModel = get_user_model()


class UserForm(forms.ModelForm):

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'autocomplete': 'off',
                'required': 'required',
            })
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'autocomplete': 'off',
                'required': 'required',
            })
    )

    class Meta:
        model = UserModel
        fields = (
            'first_name',
            'last_name',
        )

marketplace/freelancers/views/job.py
from django.shortcuts import get_object_or_404
from django.views.generic.base import RedirectView
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from ..models import (
    Job,
    Accept
)
from ..forms.job import JobForm
from ..decorators import user_name
from datetime import date


class JobListView(
    LoginRequiredMixin,
    ListView
):

    model = Job
    paginate_by = 20

    def get_queryset(self):
        queryset = super(JobListView, self).get_queryset()
        queryset = queryset.filter(
            expired__gte=date.today(),
            concluded=False
        )

        return queryset


class JobCreateView(
    LoginRequiredMixin,
    CreateView
):
    model = Job
    form_class = JobForm

    @user_name
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_success_url(self):
        return reverse_lazy(
            'freelance:joblist',
        )

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super().form_valid(form)


class JobDetailView(
    LoginRequiredMixin,
    DetailView
):
    model = Job
    slug_field = 'code'

    @user_name
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class JobAcceptedRedirectView(
    LoginRequiredMixin,
    RedirectView
):

    permanent = False
    query_string = False
    # pattern_name = 'acceptedjoblist'
    url = reverse_lazy('freelance:acceptedjoblist')

    def get_redirect_url(self, *args, **kwargs):
        job = get_object_or_404(
            Job,
            code=kwargs['code'],
            expired__gte=date.today(),
            concluded=False
        )

        if job.available:
            obj, created = Accept.objects.update_or_create(
                job=job,
                user=self.request.user,
            )
        else:
            messages.warning(self.request, 'The job cannot be assigned.')

        return super().get_redirect_url(*args, **kwargs)


class AcceptedJobListView(
    LoginRequiredMixin,
    ListView
):
    model = Job
    paginate_by = 20

    def get_queryset(self):
        queryset = super(AcceptedJobListView, self).get_queryset()
        queryset = queryset.filter(
            accept__user=self.request.user,
            accept__reject=False
        )

        return queryset

marketplace/freelancers/views/user.py
from django.views.generic import (
    UpdateView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from ..forms.user import UserForm
from django.contrib.auth import get_user_model
UserModel = get_user_model()


class UserUpdateView(
    LoginRequiredMixin,
    UpdateView
):
    model = UserModel
    form_class = UserForm
    slug_field = 'username'

    def get_success_url(self):
        return reverse_lazy(
            'freelance:joblist',
        )

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super().form_valid(form)

    def get_queryset(self):
        queryset = super(UserUpdateView, self).get_queryset()
        queryset = queryset.filter(
            id=self.request.user.id,
        )

        return queryset

marketplace/freelancers/views/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'base.html'

marketplace/freelancers/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
{% include "header.html" %}
<body>

  {% include "navbar.html" %}
  
{% block content %}
  {% if request.user.is_authenticated %}
 
  <!-- Full Page Intro -->
  <div class="view full-page-intro" style="background-image: url('{% static "img/pants-1255851_1280.jpg" %}'); background-repeat: no-repeat; background-size: cover;">

    <!-- Mask & flexbox options-->
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

      <!-- Content -->
      <div class="container">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 mb-4 white-text text-center text-md-left">

            <h1 class="display-4 font-weight-bold">Find your ideal job</h1>

            <hr class="hr-light">

            <p>
              <strong>Freelance job, opportunity to use your skills, money reward and only chosen by you own.</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>.</strong>
            </p>

            <a href={% url "freelance:joblist" %} class="btn btn-indigo btn-lg">Search
              <i class="fas fa-list ml-2"></i>
            </a>

          </div>
          <!--Grid column-->


        </div>
        <!--Grid row-->

      </div>
      <!-- Content -->

    </div>
    <!-- Mask & flexbox options-->

  </div>
  <!-- Full Page Intro -->
  {% else %}
    
  
  <!-- Full Page Intro -->
  <div class="view full-page-intro" style="background-image: url('{% static "img/office-620817_1920.jpg" %}'); background-repeat: no-repeat; background-size: cover;">

    <!-- Mask & flexbox options-->
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

      <!-- Content -->
      <div class="container">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 mb-4 white-text text-center text-md-left">

            <h1 class="display-4 font-weight-bold">Find your ideal job</h1>

            <hr class="hr-light">

            <p>
              <strong>Freelance job, opportunity to use your skills, money reward and only chosen by you own.</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>.</strong>
            </p>

            <a href={% url "registration_register" %} class="btn btn-indigo btn-lg">Create your accout
              <i class="fas fa-graduation-cap ml-2"></i>
            </a>

          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-6 col-xl-5 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card content-->
              <div class="card-body">
                {% include "registration/login_form.html" %}

              </div>

            </div>
            <!--/.Card-->

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

      </div>
      <!-- Content -->

    </div>
    <!-- Mask & flexbox options-->

  </div>
  <!-- Full Page Intro -->
  {% endif %}
{% endblock content %}

{% include "footer.html" %}
{% block extrajs %}
  
{% endblock extrajs %}
</body>

</html>

marketplace/freelancers/templates/footer.html
{% load staticfiles %}
  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
     
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/justdjangocode" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://www.twitter.com/justdjangocode" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/channel/UCRM1gWNTDx0SHIqUJygD-kQ" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>


      <a href="https://justdjango.com" target="_blank">
        <i class="fas fa-link mr-3"></i>
      </a>

     
      <a href="https://github.com/justdjango/" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://justdjango.com" target="_blank"> JustDjango.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src={% static "js/jquery-3.4.1.min.js" %}></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src={% static "js/popper.min.js" %}></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src={% static "js/bootstrap.min.js" %}></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src={% static "js/mdb.min.js" %}></script>
  <!-- Initializations -->

marketplace/freelancers/templates/freelancers/job_base.html
{% extends "base.html" %}

marketplace/freelancers/templates/freelancers/job_card.html
<!-- Card -->
<div class="card">

  <!-- Button -->

  <!-- Card content -->
  <div class="card-body">

    <!-- Title -->
    <h4 class="card-title">
      <a href={% url "freelance:jobdetail" object.code %} class="text-dark">
          {{ object.title }}
      </a>
  </h4>
    <h6 class="card-title">{{ object.user.get_full_name }}</h6>
    <hr>
    <!-- Text -->
    <p class="card-text">{{ object.description|linebreaksbr }}</p>

  </div>

  <!-- Card footer -->
  <div class="rounded-bottom mdb-color lighten-3 text-center pt-3">
    <ul class="list-unstyled list-inline font-small">
      <li class="list-inline-item pr-2 white-text">Opportunity expire at <i class="far fa-clock pr-1"></i> {{ object.expired }}</li>

      <li class="list-inline-item white-text"><i class="fab dollar-sign pr-1"> </i>$ {{ object.budget }}</li>
    </ul>
  </div>

</div>
<!-- Card -->

marketplace/freelancers/templates/freelancers/job_detail.html
{% extends "freelancers/job_base.html" %}


{% block content %}
      <!--Main layout-->
<main>
    <div class="container">

      <div class="row justify-content-center mt-4">
      
        <div class="col-md-10 mt-2">
        {% include "freelancers/job_card.html" %}


        {% if object.available %}
        <div class="text-center">
            <a href={% url "freelance:acceptjob" object.code %} class="btn btn-blue-grey">Take the job</a> 
         </div>
        {% endif %}

        </div>
  

    </div>


    </div>
</main>
  <!--Main layout-->    
{% endblock content %}

marketplace/freelancers/templates/freelancers/job_form.html
{% extends "freelancers/job_base.html" %}


{% block content %}
      <!--Main layout-->
<main>
    <div class="container">

        <!-- Material form register -->
<div class="card">

    <h5 class="card-header info-color white-text text-center py-4">
        <strong>Create a job opportunity</strong>
    </h5>

    <!--Card content-->
    <div class="card-body px-lg-5 pt-0">

        <!-- Form -->
        <form class="text-center" style="color: #757575;" action="." method="post">

        {% csrf_token %}
            <!-- E-mail -->
            <div class="md-form mt-0">
                {{ form.title }}
                <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
                
            </div>


            <div class="form-row">
                <div class="col">
                    <div class="md-form">
                         <label for="{{ form.budget.id_for_label }}">{{ form.budget.label }}: </label>
                            {{ form.budget }}
                      <div>
                          {% if form.budget.errors %}
                            <div class="errorlist form-text ">
                                {% for error in form.budget.errors  %}
                                <div>{{ error }}</div>
                                {% endfor %}
                            </div>
                            
                        {% endif %}
                        <small id="{{ form.budget.id_for_label }}" class="form-text text-muted mb-4">
                            {{ form.budget.help_text }}
                        </small>
                      </div>
                        
                    </div>
                </div>
                <div class="col">
                    
                    <div class="md-form">
                     
                            {{ form.expired }}
                      <div>
                          {% if form.expired.errors %}
                            <div class="errorlist form-text ">
                                {% for error in form.expired.errors  %}
                                <div>{{ error }}</div>
                                {% endfor %}
                            </div>
                            
                        {% endif %}
                        <small id="{{ form.expired.id_for_label }}" class="form-text text-muted mb-4">
                            {{ form.expired.help_text }}
                        </small>
                      </div>
                    </div>
                </div>
            </div>

            <div class="md-form">
                 <label for="{{ form.description.id_for_label }}">{{ form.description.label }}: </label>
                        {{ form.description }}
                  <div>
                      {% if form.description.errors %}
                        <div class="errorlist form-text ">
                            {% for error in form.description.errors  %}
                            <div>{{ error }}</div>
                            {% endfor %}
                        </div>
                        
                    {% endif %}
                    <small id="defaultRegisterFormPhoneHelpBlock" class="form-text text-muted mb-4">
                        {{ form.description.help_text }}
                    </small>
                  </div>
                    
        
            </div>

       

            <!-- Sign up button -->
            <button class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0" type="submit">Save</button>

         
        </form>
        <!-- Form -->

    </div>

</div>
<!-- Material form register -->


    </div>
</main>
  <!--Main layout-->    
{% endblock content %}

marketplace/freelancers/templates/freelancers/job_list.html
{% extends "freelancers/job_base.html" %}


{% block content %}
      <!--Main layout-->
<main>
    <div class="container">

      {% if messages %}
      <div class="row justify-content-center mt-4">
      <div class="col-md-12 mt-2">
        <ul class="messages">
          {% for message in messages %}
          <div class="alert alert-danger {{ message.tags }}" role="alert">
            {{ message }}
          </div>
          {% endfor %}
        </ul>
      </div>
      </div>
      {% endif %}
      

    <div class="row mt-4">
    {% for object in object_list %}
        <div class="col-md-6 mt-2">
        {% include "freelancers/job_card.html" %}
        </div>
    {% empty %}
        <div class="alert alert-warning text-center" role="alert">
          <p>Humm is nothing here!</p>
          <p>Try <a href={% url "freelance:joblist" %}> this</a></p>
        </div>

    {% endfor %}

    </div>

  {% include "pages.html" %}

    </div>
</main>
  <!--Main layout-->    
{% endblock content %}

marketplace/freelancers/templates/header.html
{% load staticfiles %}


<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>
    {% block title %}Freelancer Marketplace{% endblock title %}
</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href={% static "css/bootstrap.min.css" %} rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href={% static "css/mdb.min.css" %} rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href={% static "css/style.min.css" %} rel="stylesheet">
  <style type="text/css">
    html,
    
    header,
    .view {
      height: 100%;
    }

    @media (max-width: 740px) {
      html,
      
      header,
      .view {
        height: 1000px;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {
      html,
      
      header,
      .view {
        height: 650px;
      }
    }
    @media (min-width: 800px) and (max-width: 850px) {
              .navbar:not(.top-nav-collapse) {
                  background: #1C2331!important;
              }
          }

    main {
      margin-top: 80px;

    }

    body {
      min-height: 100vh;
    }

    footer {
      position: block;
      left: 0;
      bottom: 0;
      width: 100%;
      background-color: #343a40;
      color: #f8f9fa;
      text-align: center;
      
    }

  </style>
</head>

marketplace/freelancers/templates/navbar.html
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand" 

      {% if request.user.is_authenticated %}
        href={% url "freelance:acceptedjoblist" %}
      {% else %}
        href={% url "freelance:index" %}
      {% endif %}

      >
        <strong>FreeMarket</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

      {% if request.user.is_authenticated %}
        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href={% url "freelance:joblist" %}>Jobs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url "freelance:jobcreate" %} >Create Job</a>
          </li>
        </ul>
      {% endif %}

        <!-- Right -->
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href={% url "freelance:userupdate" request.user.username %}>Update Profile</a>
            </li>
              <a href={% url "auth_logout" %} class="nav-link">
                <i class="fas fa-sign-out-alt"></i>Logot
              </a>
            {% else %}

              <a href={% url "auth_login" %} class="nav-link">
                <i class="fas fa-sign-in-alt"></i>Login
              </a>
            {% endif %}
          </li>
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

marketplace/freelancers/templates/pages.html
{% if page_obj %}

<div class="row justify-content-center">

<div class="col-sm-12 col-md-12 mt-4 mb-2">
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if query %}&query={{ query }}{% endif %}{% if urlget %}&{{ urlget }}{% endif %}">Previous</a>
            </li>
        {% endif %}
        <span class="page-item active">
            <a href="#" class="page-link">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </a>
        </span>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if query %}&query={{ query }}{% endif %}{% if urlget %}&{{ urlget }}{% endif %}">Next</a>
          </li>
        {% endif %}

      </ul>
    </nav>

</div>
</div>

{% endif %}